[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_program = "Dr2LaX8WUP2uzr3uoeXWZamC6CwBk47kiLnTKu2AihQE"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
